version: '3.8'
services:
  service:
    image: 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
